# English content: slug -> (title, intro, items, faq)
EN = {
"autohuolto-ja-korjaus": ("Servicing and repair",
 "We service and repair all car brands in Espoo. A warning light is on, the car makes a strange noise or a scheduled service is due – we first find the cause and tell you honestly what the repair really needs. We only do what is necessary.",
 ["Fault finding and computer diagnostics","Oil and filter change","Brakes: pads and discs","Chassis, suspension and steering","Electrical and battery check"],
 [("A warning light is on – can I keep driving?","It depends on the light. A red warning light usually means you should stop driving immediately. Yellow or orange needs a check soon. Call us and we will advise based on your situation."),
  ("How often should a car be serviced?","Follow the manufacturer's service schedule – often once a year or every 15,000–30,000 km."),
  ("Do you give a price before starting work?","Yes. We give an estimate in advance and do no repairs without your agreement.")]),
"tuulilasien-vaihto": ("Windscreen replacement",
 "We replace windscreens and repair stone chips. A small chip is best repaired right away: then it does not spread into a crack and the whole windscreen does not need to be replaced.",
 ["Windscreen replacement","Stone chip repair","Side and rear windows","Check of seals and trims during replacement"],
 [("Can a stone chip be repaired, or does the glass need replacing?","A small chip can usually be repaired if it is not directly in the driver's line of sight or at the edge of the glass. Otherwise the glass is replaced."),
  ("Can I drive straight after replacement?","Adhesive curing time varies. We will tell you the exact waiting time when we do the work."),
  ("Does insurance cover glass damage?","Many insurance policies cover glass damage. Check the terms with your insurer.")]),
"pdr-korikorjaukset": ("Body repair (PDR)",
 "PDR (Paintless Dent Repair) means removing a dent without repainting. The dent is pushed back into shape with special tools, so the original paint stays intact. It is often faster and cheaper than traditional repair.",
 ["Parking dings and door-edge dents","Hail damage","Dents on the bonnet, roof and wings","Dent assessment before work"],
 [("Is PDR suitable for every dent?","No. The method works when the paint is intact and the dent is not too sharp or deep. We give an honest assessment, even when PDR is not suitable."),
  ("Is the paint damaged?","No, when the paint is intact. The surface is not repainted, so the original paint is preserved."),
  ("How long does the repair take?","A small dent can be done quickly. The exact time becomes clear at the assessment.")]),
"kiillotus-ja-keraaminen-pinnoitus": ("Polishing & ceramic coating",
 "Polishing removes fine scratches, dullness and fading from the paint. A ceramic coating protects the cleaned surface for a long time and makes washing easier.",
 ["Body polishing","Headlight polishing","Ceramic coating","Pre-wash and surface preparation"],
 [("Does polishing remove all scratches?","Not always. Light scratches disappear. Deep scratches you can feel with a fingernail often need spot painting. We assess before starting."),
  ("How long does a ceramic coating last?","It depends on the product, how the car is used and how it is cared for. We tell you the expected durability of the chosen coating before the work."),
  ("Does a coated car need special care?","Wash it gently by hand or touchless. Avoid coarse brushes.")]),
"ruostekorjaus-ja-paikkamaalaus": ("Rust repair & spot painting",
 "Rust spreads if it is not repaired in time. We remove the rust damage, treat the surface and paint the repaired area in the car's colour.",
 ["Rust removal and treatment","Spot painting","Painting a panel","Repair of scratches and stone chips"],
 [("Can rust be stopped?","Surface rust can be removed and the surface protected. If the metal has already rusted through, body repair is usually needed. We look at the situation and explain your options."),
  ("Will the colour match exactly?","The shade is matched to the car's colour. Old paint may show a small difference because paint fades over time."),
  ("Is it worth repairing rust immediately?","Yes. Rust keeps progressing, and the earlier it is repaired, the cheaper it is.")]),
"sisapesu-ja-detailing": ("Interior cleaning & detailing",
 "Thorough interior cleaning and detailing restore the car's tidy look. We clean seats, mats, plastics and windows, focusing on what the car really needs.",
 ["Interior cleaning and vacuuming","Deep cleaning of seats and mats","Leather cleaning and care","Finishing of plastics and windows","Full detailing inside and out"],
 [("Will the stain definitely come out?","Most stains do. Old or strongly staining marks (coffee, grease, ink) do not always. We assess the stain before starting."),
  ("How long do the seats take to dry?","Drying time depends on the material and method. We tell you at handover."),
  ("Do you care for leather seats?","Yes, we clean and care for leather surfaces.")]),
"autojen-teippaukset": ("Car wrapping",
 "Wrapping changes the car's look and protects the paint. We do full and partial wraps and colour changes, and choose the shade and film together with you.",
 ["Full car wrap","Partial wrap: roof, bonnet, mirrors","Colour change","Design and colour choice together"],
 [("Does the wrap damage the paint?","A quality film does not damage intact original paint. Previously repainted or damaged surfaces may come off with the film."),
  ("How long does a wrap last?","Lifespan depends on the film quality, how the car is used and how it is cared for."),
  ("How should a wrapped car be washed?","By hand or touchless. Avoid pointing a pressure washer directly at the edges and avoid brush washes.")]),
"suojakalvot": ("Protective films",
 "Protective film (PPF) is a transparent film that protects the paint from stones, sand and scratches. It is especially useful on the front of the car, where most impacts happen.",
 ["Front-end protection: bumper, bonnet, wings, mirrors","Full-car protective film","Individual parts, e.g. sills and door-handle recesses"],
 [("Is the film visible?","A quality film is almost invisible and does not change the shade of the paint."),
  ("Can the film be fitted to an older car?","Yes, as long as the paint is intact. The surface is cleaned and, if needed, polished before installation."),
  ("How do I care for the film?","Wash regularly and gently. Avoid strong solvents.")]),
}
